modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="taa"
version="1.1.2"
displayName="Tacz Attribute Add"
description="Adds additional attributes and functionality to TACZ guns"
authors="xlxyvergil"

[[dependencies.taa]]
modId="forge"
mandatory=true
versionRange="[47.3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.taa]]
modId="tacz"
mandatory=true
versionRange="[1.1.6,)"
ordering="NONE"
side="BOTH"